### ISSUE TITLE
Controller CrashLoopBackOff after fresh install

### ISSUE THREAD

**Issue by amsatique** [outscale-dev/osc-bsu-csi-driver#247]
/kind bug

**What happened?**
During installation of driver i have ebs-csi-controller in CrashLoopBackOff in Kubernetes v1.23.5.
I have checked the pod logs and having this trace:
```
I0707 15:24:13.882407 1 driver.go:63] Driver: ebs.csi.aws.com Version: v0.0.15
panic: could not get metadata from OSC: EC2 instance metadata is not available
goroutine 1 [running]:
github.com/outscale-dev/osc-bsu-csi-driver/pkg/driver.newControllerService(0xc0001de960)
/build/pkg/driver/controller.go:83 +0x85
github.com/outscale-dev/osc-bsu-csi-driver/pkg/driver.NewDriver({0xc000517f58, 0x3, 0x40cef4})
/build/pkg/driver/driver.go:83 +0x579
main.main()
/build/cmd/main.go:31 +0x18f
```

I've checked my env vars, all seems to be ok (osc-csi-bsu secret is available on namespace):
```
[...]
  env:
    - name: CSI_ENDPOINT
      value: 'unix:///var/lib/csi/sockets/pluginproxy/csi.sock'
    - name: OSC_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: osc-csi-bsu
          key: access_key
          optional: true
    - name: OSC_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: osc-csi-bsu
          key: secret_key
          optional: true
    - name: AWS_REGION
      value: eu-west-2
[...]
```

I do not use any Network Policies on my namespace (i'have seen some thread saying that can be related)
My cluster have acces to internet

**What you expected to happen?**
EBS-CSI is working well and allow to create pv/pvc

**How to reproduce it (as minimally and precisely as possible)?**
On fresh Kubernetes, follow steps of this documentation:
https://github.com/outscale-dev/osc-bsu-csi-driver/blob/OSC-MIGRATION/docs/deploy.md

**Anything else we need to know?**:

**Environment**
- Kubernetes version:
  Kubernetes Version: v1.23.5+b0357ed
- Driver version:
  v0.0.15
